# This is a basic workflow to help you get started with Actions

name: R Conda

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: recetox-xmsannotator-dev
          auto-update-conda: true
          environment-file: conda/environment-dev.yaml
          auto-activate-base: false
      - run: |
          conda init bash
          conda env list
      - name: Fetch batch1_neg test data
        run: wget -P xmsannotator/tests/testthat/test-data/batch1_neg -i xmsannotator/tests/remote-files/fetch_batch1_neg.txt
      - name: Fetch qc_solvent test data
        run: wget -P xmsannotator/tests/testthat/test-data/qc_solvent -i xmsannotator/tests/remote-files/fetch_qc_solvent.txt
      - name: Fetch sourceforge test data
        run: wget -P xmsannotator/tests/testthat/test-data/sourceforge -i xmsannotator/tests/remote-files/fetch_sourceforge.txt
      - name: Fetch qc_matrix test data
        run: wget -P xmsannotator/tests/testthat/test-data/qc_matrix -i xmsannotator/tests/remote-files/fetch_qc_matrix.txt
      - name: Test coverage
        run: |
          conda activate recetox-xmsannotator-dev
          options(covr.gcov="")
          Rscript -e "covr::codecov('xmsannotator', quiet = FALSE)"
